/**
 * The shared social preview generated by app/opengraph-image.tsx.
 * Next.js only inherits that image on pages that leave `openGraph` unset,
 * so pages with their own openGraph block list it explicitly.
 */
export const socialImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "BITDOT Consulting Services: AI career development, automation training, governance and risk advisory",
} as const;
